TARGET_BOOTLOADER_BOARD_NAME := fujitsu_stylistic

# Arch
TARGET_ARCH_VARIANT := x86

# Stylus
BOARD_USES_WACOMINPUT := true

# Video
BOARD_GPU_DRIVERS := i915g
BOARD_USES_DRM := true

BOARD_KERNEL_CMDLINE += video=LVDS-1:d video=1024x768 i915.modeset=1

# Apps
TARGET_HAS_THIRD_PARTY_APPS := true

# Sensors
BOARD_USES_STYLISTICBUTTONS := true
#BOARD_USES_STYLISTICSENSORS := true
BOARD_USES_KBDSENSOR_ROTKEY1 := true

include $(GENERIC_X86_CONFIG_MK)

TARGET_BOOTLOADER_BOARD_NAME := fujitsu_stylistic
