TARGET_BOOTLOADER_BOARD_NAME := fujitsu_stylistic

# Arch
TARGET_ARCH_VARIANT := x86

# Stylus
BOARD_USES_WACOMINPUT := true
BOARD_USES_TSLIB := false

# Audio
BOARD_USES_ALSA_AUDIO := true
BUILD_WITH_ALSA_UTILS := true

# Video
BOARD_GPU_DRIVERS := i915g

# Apps
TARGET_HAS_THIRD_PARTY_APPS := true

# Sensors
BOARD_USES_STYLISTICBUTTONS := true
#BOARD_USES_STYLISTICSENSORS := true
BOARD_USES_KBDSENSOR_ROTKEY1 := true

include $(GENERIC_X86_CONFIG_MK)

TARGET_BOOTLOADER_BOARD_NAME := fujitsu_stylistic
